### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [damiand33/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by damiand33** [comment]
Billy,

Thanks for looking at my app.  I did some research and added the viewport meta tag to the head section of my html file.  I found another cool feature in Chrome that lets me see how my page looks on different devices like iPads, iPhones, etc.  After I added the viewport meta tag, everything adjusted for the different mobile devices.

Best,
Damian
